# GitLab CI/CD configuration file for 1dv613 project course
stages:
  - lint
  - build
  - deploy

# Code linting
lint-job:
  stage: lint
  image: node:20-bullseye
  script:
    - cd mobile
    - echo "Installing dependencies..."
    - npm install
    - npx install-peerdeps --dev @lnu/eslint-config
    - echo "Linting..."
    - echo "Finding JSX files..."
    - find . -name "*.jsx" -o -name "*.js" -o -name "*.ts" -o -name "*.tsx" | grep -v "node_modules"
    - npx eslint --ext .js,.jsx,.ts,.tsx . --ignore-pattern "node_modules/" || true

# Build the application
build-job:
  stage: build
  image: node:20-bullseye
  script:
    - cd mobile
    - echo "Installing dependencies..."
    - npm install
    - echo "Building application..."
    - npm run build || echo "Skipping build step for Expo project"
  artifacts:
    paths:
      - mobile/
    expire_in: 1 week
  needs:
    - lint-job

# Deploy the application to Render using the API
deploy-job:
  stage: deploy
  image: curlimages/curl:latest
  environment:
    name: production
    url: https://mycookbook-nijb.onrender.com
  script:
    - |
      echo "Deploying to Render..."
      curl -X POST "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
        -H "Authorization: Bearer $RENDER_API_KEY" \
        -H "Content-Type: application/json"
      echo "Deployment triggered successfully!"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  needs:
    - build-job